version: '3.8'

services:
  mono-api:
    image: bjs24/mono-api:latest
    container_name: mono-api
    ports:
      - "3001: 3000"

    environment:
      MONGO_URL: ${MONGO_URL_DOCKER}
      PORT: ${PORT}
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_USER: ${MAIL_USER}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}

    depends_on:
      - mongoDB
    
  mongoDB: 
    image: mongo
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongodb_api_volume:/data/db
volumes:
  mongodb_api_volume: